Rozdělení částí afterDeploye
AppsDevTeam/AfterDeploy pull request #1
Opened 2017-05-15 13:18 UTC by Blizqery

Rozdělení na část instalační (bez závislosti na nette) a extension část. Dělá se aby se composer a bower závislosti nainstalovali dříve než se spustí aplikace, aby se vyhnulo chybám loader nemůže nalézt třídu, která ještě nebyla nainstalována

2017-05-16 14:09 UTC, Danoha requested changes

2017-05-16 14:09 UTC, Danoha commented on src/Deployment.php
> +		if (!static::shouldStartDeploy($config)) {
Na základě:
> the key has to be same as the one defined in bootstrap.php

Neměli bychom tu vyhodit výjimku, když někdo zapomene ten klíč změnit na 2 místech? Aby se pak nedivil, že se mu děje jen půlka afterDeploye.

2017-05-16 14:09 UTC, Danoha commented on src/Deployment.php
> +		if (static::shouldStartDeploy($config)) {
Nemělo by tu být `!static::shouldStartDeploy($config)` ?

2017-05-16 14:09 UTC, Danoha commented on src/Deployment.php
> +		$key = isset($config['key']) && !empty($config['key']) ? $config['key'] : self::DEFAULT_KEY;
Proč se dělá `isset` a potom `!empty`, když `!empty` zahrnuje `isset`?

2017-05-16 14:09 UTC, Danoha commented on src/Deployment.php
> +		$key = isset($config['key']) && !empty($config['key']) ? $config['key'] : self::DEFAULT_KEY;
Pro jistotu použít `static::DEFAULT_KEY`.

2017-05-17 07:21 UTC, michallohnisky commented on src/Deployment.php
> +		if (!static::shouldStartDeploy($config)) {
Tak v tom případě bych ho nenechával zadávat 2x. Config k deploymentu (jako je `key`) by se dal zadat pouze jednou a to v bootstrapu, ale config k ostatním (jako je redis) by zůstal v neonu jako je teď. Tento deployment config (`key`, ...) by se uložil do statické proměnné a pak se používal i v druhé části.

2017-05-18 11:44 UTC, Danoha approved these changes

2017-05-26 11:22 UTC, Blizqery commented on src/Deployment.php
> +		if (!static::shouldStartDeploy($config)) {
Hotovo

2017-05-26 11:22 UTC, merged